name: Replace wp-json

on:
  push:
    branches: [main]

jobs:
  replace-string:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
        
      - name: Replace wp-json
        run: |          
          find . -type f \( -name "*.js" -o -name "*.html" \) -exec sed -i 's/\/wp-json/https:\/\/rreya.com\/wp-json\//g' {} +
          
      - name: Commit Changes
        run: |
          git config --global user.email "aravind_n_c@yahoo.co.in"
          git config --global user.name "Aravind NC"
          git commit -am "Replace /wp-json with https://rreya.com/wp-json"
          git push

      - name: Allow github-actions bot to push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.PAT_TOKEN }}'
