name: Replace wp-json in HTML

on:
  push:
    branches: [main]

jobs:
  replace-string:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Replace wp-json
        run: |
          find . -name "*.html" -type f -print0 | xargs -0 sed -i 's/\/wp-json/https:\/\/rreya.com\/wp-json/g'
          
      - name: Commit Changes
        run: |
          git config --global user.email "aravind_n_c@yahoo.co.in"
          git config --global user.name "GIT Workflow"
          git commit -am "Replace /wp-json with https://rreya.com/wp-json"
          git push
